insert into MinderRanking values(1,'Jeef Curve','Warrior Curve','A. F. Kay','57944','C');
insert into MinderRanking values(2,'Slow Rafaam Curve','Rafaam Curve','Akazamzarak','58021','C');
insert into MinderRanking values(3,'3 on 3 ','Fast Basic Curve','Al Akir','64403','C');
insert into MinderRanking values(4,'Fast Basic Curve','Slow Jeef Curve','Alexstrasza','61488','C');
insert into MinderRanking values(5,'None','None','Aranna ','61910','D');
insert into MinderRanking values(6,'Rafaam Curve','Fast Jeef Curve','Barov','58044',' A+');
insert into MinderRanking values(7,'Fast Basic Curve','3 on 3 ','Blackthorn','63319','C');
insert into MinderRanking values(8,'Warrior Curve','Basic Curve','Brann','71458',' A+');
insert into MinderRanking values(9,'Basic Curve','Slow Jeef Curve','Bigglesworth','60214','C');
insert into MinderRanking values(10,'Fast Basic Curve','Jeef Curve','Brukan','79719','D');
insert into MinderRanking values(11,'Fast Basic Curve','Toki Curve','Cariel','73940','D');
insert into MinderRanking values(12,'Warrior Curve','Slow Jeef Curve','Chenvaala','64475','C');
insert into MinderRanking values(13,'3 on 3 ','Fast Basic Curve','Cookie','77516','S');
insert into MinderRanking values(14,'Aggro Yogg Curve','None','Cthun','58535','D');
insert into MinderRanking values(15,'Fast Basic Curve','Slow Jeef Curve','Curator','59203','C');
insert into MinderRanking values(16,'Warrior Curve','None','Deathwing','60369','D');
insert into MinderRanking values(17,'None','Slow Rafaam Curve','Deryl','59806','C');
insert into MinderRanking values(18,'3 on 3 ','Fast Basic Curve','Drek''Thar','80239','F');
insert into MinderRanking values(19,'Slow Rafaam Curve','Rafaam Curve','Edwin','57633','D');
insert into MinderRanking values(20,'Fast Basic Curve','3 on 3 ','Elise','60213','C');
insert into MinderRanking values(21,'Rafaam Curve','None','Eudora','62242','C');
insert into MinderRanking values(22,'None','None','Finley','60211',' A-');
insert into MinderRanking values(23,'Basic Curve','None','Flurgl','60372','F');
insert into MinderRanking values(24,'Slow Rafaam Curve','Rafaam Curve','Galakrond','57635','B');
insert into MinderRanking values(25,'3 on 3 ','None','Galewing','75702',' A+');
insert into MinderRanking values(26,'Warrior Curve','None','Gallywix','57891','S');
insert into MinderRanking values(27,'Basic Curve','Slow Jeef Curve','George','57929','B');
insert into MinderRanking values(28,'Jeef Curve','3 on 3','Greybough','67553','C');
insert into MinderRanking values(29,'None','None','Guff','68129','F');
insert into MinderRanking values(30,'Jeef Curve','Warrior Curve','Hooktusk','62266','S');
insert into MinderRanking values(31,'3 on 3 ','None','Illidan','57634','D');
insert into MinderRanking values(32,'Slow Jeef Curve','Fast Basic Curve','Jandice','63601','S');
insert into MinderRanking values(33,'Warrior Curve','Slow Rafaam Curve','Jaraxxus','59807','D');
insert into MinderRanking values(34,'Basic Curve','Slow Jeef Curve','Kaelthas','61912','C');
insert into MinderRanking values(35,'Fast Basic Curve','Slow Jeef Curve','Kragg','62268','C');
insert into MinderRanking values(36,'Basic Curve','Slow Jeef Curve','Kurtrus','74631','C');
insert into MinderRanking values(37,'Jeef Curve','3 on 3 ','Lich Bazhial','58024',' A+');
insert into MinderRanking values(38,'3 on 3 ','Fast Basic Curve','Lich King','63602','B');
insert into MinderRanking values(39,'Rafaam Curve','None','Maiev','61914',' A+');
insert into MinderRanking values(40,'Warrior Curve','Jeef Curve','Malygos','61490',' A-');
insert into MinderRanking values(41,'Slow Jeef Curve','Warrior Curve','Millhouse','60366','B');
insert into MinderRanking values(42,'Warrior Curve','3 on 3 ','Millificent','57946','D');
insert into MinderRanking values(43,'Rafaam Curve','Toki Curve','Mukla','59814','C');
insert into MinderRanking values(44,'Jeef Curve','None','Mutanus','71916',' A-');
insert into MinderRanking values(45,'3 on 3 ','Fast Basic Curve','Nguyen','71908',' A+');
insert into MinderRanking values(46,'Fast Basic Curve','Slow Jeef Curve','Nozdormu','61489','C');
insert into MinderRanking values(47,'Toki Curve','Warrior Curve','Nzoth','66483','C');
insert into MinderRanking values(48,'Fast Basic Curve','Slow Jeef Curve','Omu','63604',' A+');
insert into MinderRanking values(49,'Jeef Curve','Warrior Curve','Onyxia','82110','D');
insert into MinderRanking values(50,'Toki Curve','Fast Basic Curve','Patches','57947','C');
insert into MinderRanking values(51,'3 on 3 ','Fast Basic Curve','Patchwerk','59397','C');
insert into MinderRanking values(52,'Rafaam Curve','None','Pyramad','59831','D');
insert into MinderRanking values(53,'Rafaam Curve','None','Rafaam','60362','S');
insert into MinderRanking values(54,'Slow Jeef Curve','Basic Curve','Ragnaros','57892','D');
insert into MinderRanking values(55,'Fast Basic Curve','Slow Jeef Curve','Rakanishu','64400','F');
insert into MinderRanking values(56,'Slow Jeef Curve','None','Rat King','57893','D');
insert into MinderRanking values(57,'Warrior Curve','None','Reno Jackson','60212',' A-');
insert into MinderRanking values(58,'Jeef Curve','Fast Basic Curve','Rokara','70838','B');
insert into MinderRanking values(59,'Rafaam Curve','None','Saurfang','71454','C');
insert into MinderRanking values(60,'Aggro Yogg Curve','Warrior Curve','Scabbs','76562','S');
insert into MinderRanking values(61,'Warrior Curve','None','Shudderwock','58027','S');
insert into MinderRanking values(62,'Fast Basic Curve','3 on 3 ','Silas','64480',' A-');
insert into MinderRanking values(63,'Fast Basic Curve','None','Sindragosa','58435','D');
insert into MinderRanking values(64,'Warrior Curve','None','Sneed','76521','C');
insert into MinderRanking values(65,'Slow Jeef Curve','Fast Basic Curve','Tamsin','74646','C');
insert into MinderRanking values(66,'Jeef Curve','Fast Basic Curve','Tavish Stormpike','77987','D');
insert into MinderRanking values(67,'Warrior Curve','Slow Jeef Curve','Tess','60367','B');
insert into MinderRanking values(68,'Fast Basic Curve','Slow Jeef Curve','Tickatus','67356','B');
insert into MinderRanking values(69,'Toki Curve','Fast Basic Curve','Toki','58534','C');
insert into MinderRanking values(70,'Slow Jeef Curve','None','Vanndar ','80247','D');
insert into MinderRanking values(71,'Fast Basic Curve','None','Varden','79615','B');
insert into MinderRanking values(72,'Warrior Curve','None','Voljin','71463',' A+');
insert into MinderRanking values(73,'Rafaam Curve','None','Wagtoggle','57924','D');
insert into MinderRanking values(74,'Aggro Yogg Curve','Basic Yogg Curve','Xyrella','70956',' A+');
insert into MinderRanking values(75,'Aggro Yogg Curve','Basic Yogg Curve','Yogg','59805','B');
insert into MinderRanking values(76,'Jeef Curve','None','Ysera','60370','D');
insert into MinderRanking values(77,'Fast Basic Curve','Basic Yogg Curve','Yshaarj','66196','B');
insert into MinderRanking values(78,'Fast Basic Curve','Slow Jeef Curve','Zephrys','64485','B');
insert into MinderRanking values(79,'Fast Basic Curve','None','Ambassador Faelin',81569,' A+');
insert into MinderRanking values(80,'Warrior Curve','Fast Jeef Curve','Ini Stormcoil',80832,'F');
insert into MinderRanking values(81,'Warrior Curve','None','Queen Azshara',79618,'A-');
insert into MinderRanking values(82,'3 on 3','Warrior Curve','Ozumat',86013,'C');
SELECT SETVAL ('minder_ranking_seq', '82');

