INSERT INTO DeckTrackerHeroNameMapping VALUES ('AFKay','A. F. Kay');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Azshara','Queen Azshara');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('AlAkir','Al''Akir');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Aranna','Aranna Starseeker');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Alexstrasza','Alexstrasza');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Ysera','Ysera');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Ini','Ini Stormcoil');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Illidan','Illidan Stormrage');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Vanndar','Vanndar Stormpike');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Varden','Varden Dawngrasp');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Voljin','Vol''jin');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Edwin','Edwin VanCleef');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Elise','Elise Starseeker');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Onyxia','Onyxia');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Guff','Guff Runetotem');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Galakrond','Galakrond');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Kurtrus','Kurtrus Ashfallen');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Cariel','Cariel Roame');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Curator','The Curator');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Mukla','King Mukla');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('CThun','C''Thun');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Galewing','Galewing');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Kaelthas','Kael''thas Sunstrider');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Cookie','Cookie the Cook');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Silas','Silas Darkmoon');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Xyrella','Xyrella');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Saurfang','Overlord Saurfang');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Finley','Sir Finley Mrrgglton');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Chenvaala','Chenvaala');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Shudderwock','Shudderwock');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Jandice','Jandice Barov');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Sindragosa','Sindragosa');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Scabbs','Scabbs Cutterbutter');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Sneed','Sneed');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Tavish','Tavish Stormpike');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Tamsin','Tamsin Roame');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Deryl','Dancin'' Deryl');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Tickatus','Tickatus');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Tess','Tess Greymane');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Deathwing','Deathwing');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('DrekThar','Drek''Thar');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('RatKing','The Rat King');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Nozdormu','Nozdormu');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Patchwerk','Patchwerk');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Bigglesworth','Mr. Bigglesworth');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Pyramad','Pyramad');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Faelin','Ambassador Faelin');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Hooktusk','Captain Hooktusk');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Brukan','Bru''kan');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Maiev','Maiev Shadowsong');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Nguyen','Master Nguyen');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Malygos','Malygos');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Millificent','Millificent Manastorm');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Millhouse','Millhouse Manastorm');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('YShaarj','Y''Shaarj');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Eudora','Captain Eudora');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Rakanishu','Rakanishu');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('LichKing','The Lich King');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Bazhial','Lich Baz''hial');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Reno','Reno Jackson');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Rokara','Rokara');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Jaraxxus','Lord Jaraxxus');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('LordBarov','Lord Barov');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Wagtoggle','Queen Wagtoggle');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('NZoth','N''Zoth');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Akazamzarak','The Great Akazamzarak');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Zephrys','Zephrys, the Great');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Ragnaros','Ragnaros the Firelord');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Patches','Patches the Pirate');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Greybough','Greybough');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Yogg','Yogg-Saron, Hope''s End');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Brann','Dinotamer Brann');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Flurgl','Fungalmancer Flurgl');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Kragg','Skycap''n Kragg');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Blackthorn','Death Speaker Blackthorn');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Gallywix','Trade Prince Gallywix');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Omu','Forest Warden Omu');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Rafaam','Arch-Villain Rafaam');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('George','George the Fallen');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Toki','Infinite Toki');
INSERT INTO DeckTrackerHeroNameMapping VALUES ('Mutanus','Mutanus the Devourer');
