insert into TierTable values (10001, 'tier表 1',1,null,current_timestamp);
insert into TierTable values (10002, 'tier表 2',1,null,current_timestamp);
insert into TierTable values (10003, 'tier表 3',1,null,current_timestamp);
insert into TierTable values (10004, 'tier表 4',1,null,current_timestamp);
insert into TierTable values (10005, 'tier表 5',1,null,current_timestamp);
insert into TierTable values (10006, 'tier表 6',1,null,current_timestamp);
insert into TierTable values (10007, 'tier表 7',1,null,current_timestamp);
insert into TierTable values (10008, 'tier表 8',1,null,current_timestamp);
insert into TierTable values (10009, 'tier表 9',1,null,current_timestamp);
insert into TierTable values (10010, 'tier表10',1,null,current_timestamp);
insert into TierTable values (10011, 'tier表11',1,null,current_timestamp);
insert into TierTable values (10012, 'tier表12',1,null,current_timestamp);
insert into TierTable values (10013, 'tier表13',1,null,current_timestamp);
insert into TierTable values (10014, 'tier表14',1,null,current_timestamp);
insert into TierTable values (10015, 'tier表15',1,null,current_timestamp);
insert into TierTable values (10016, 'tier表16',1,null,current_timestamp);
insert into TierTable values (10017, 'tier表17',1,null,current_timestamp);
insert into TierTable values (10018, 'tier表18',1,null,current_timestamp);
insert into TierTable values (10019, 'tier表19',1,null,current_timestamp);
insert into TierTable values (10020, 'tier表20',1,null,current_timestamp);
insert into TierTable values (10021, 'tier表21',1,null,current_timestamp);
insert into TierTable values (10022, 'tier表22',1,null,current_timestamp);
insert into TierTable values (10023, 'tier表23',1,null,current_timestamp);
insert into TierTable values (10024, 'tier表24',1,null,current_timestamp);
insert into TierTable values (10025, 'tier表25',1,null,current_timestamp);
insert into TierTable values (10026, 'tier表26',1,null,current_timestamp);
insert into TierTable values (10027, 'tier表27',1,null,current_timestamp);
insert into TierTable values (10028, 'tier表28',1,null,current_timestamp);
insert into TierTable values (10029, 'tier表29',1,null,current_timestamp);
insert into TierTable values (10030, 'tier表30',1,null,current_timestamp);
insert into TierTable values (10031, 'tier表31',1,null,current_timestamp);
insert into TierTable values (10032, 'tier表32',1,null,current_timestamp);
insert into TierTable values (10033, 'tier表33',1,null,current_timestamp);
insert into TierTable values (10034, 'tier表34',1,null,current_timestamp);
insert into TierTable values (10035, 'tier表35',1,null,current_timestamp);
insert into TierTable values (10036, 'tier表36',1,null,current_timestamp);
insert into TierTable values (10037, 'tier表37',1,null,current_timestamp);
insert into TierTable values (10038, 'tier表38',1,null,current_timestamp);
insert into TierTable values (10039, 'tier表39',1,null,current_timestamp);
insert into TierTable values (10040, 'tier表40',1,null,current_timestamp);
insert into TierTable values (10041, 'tier表41',1,null,current_timestamp);
insert into TierTable values (10042, 'tier表42',1,null,current_timestamp);
insert into TierTable values (10043, 'tier表43',1,null,current_timestamp);
insert into TierTable values (10044, 'tier表44',1,null,current_timestamp);
insert into TierTable values (10045, 'tier表45',1,null,current_timestamp);
insert into TierTable values (10046, 'tier表46',1,null,current_timestamp);
insert into TierTable values (10047, 'tier表47',1,null,current_timestamp);
insert into TierTable values (10048, 'tier表48',1,null,current_timestamp);
insert into TierTable values (10049, 'tier表49',1,null,current_timestamp);
insert into TierTable values (10050, 'tier表50',1,null,current_timestamp);
insert into TierTable values (10051, 'tier表51',1,null,current_timestamp);
insert into TierTable values (10052, 'tier表52',1,null,current_timestamp);
insert into TierTable values (10053, 'tier表53',1,null,current_timestamp);
insert into TierTable values (10054, 'tier表54',1,null,current_timestamp);
insert into TierTable values (10055, 'tier表55',1,null,current_timestamp);
insert into TierTable values (10056, 'tier表56',1,null,current_timestamp);
insert into TierTable values (10057, 'tier表57',1,null,current_timestamp);
insert into TierTable values (10058, 'tier表58',1,null,current_timestamp);
insert into TierTable values (10059, 'tier表59',1,null,current_timestamp);
insert into TierTable values (10060, 'tier表60',1,null,current_timestamp);
insert into TierTable values (10061, 'tier表61',1,'[{"id":"9fdfca66-5f61-459e-9990-c5945e12c7ea","name":"S","color":"#FF8A80","heros":[{"id":3,"ban":{"exists":["2","5","6","8","7"],"notExists":["4","3","1"]},"memo":"111"},{"id":1,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":16,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":24,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":29,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":37,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":45,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":46,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":51,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":57,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":76,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":67,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":78,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":80,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":79,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":38,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":20,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":22,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":44,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":34,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":11,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":6,"ban":{"exists":[],"notExists":[]},"memo":""}],"order":0},{"id":"a3540270-b27b-4f81-a2bb-fd3efaa1503d","name":"A","color":"#FFA726","heros":[{"id":9,"ban":{"exists":["8","3","2","1"],"notExists":["6","7","5","4"]},"memo":"bbb"},{"id":5,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":15,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":23,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":31,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":36,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":55,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":2,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":43,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":39,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":56,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":58,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":66,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":68,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":77,"ban":{"exists":[],"notExists":[]},"memo":""}],"order":1},{"id":"abf55e06-c7ea-4f92-b763-c5ee47cfba55","name":"B","color":"#FFD180","heros":[{"id":35,"ban":{"exists":["7","8","4","6","5","3","2","1"],"notExists":[]},"memo":"ccc"},{"id":4,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":32,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":14,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":21,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":63,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":30,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":27,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":72,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":41,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":50,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":53,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":62,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":65,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":70,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":75,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":49,"ban":{"exists":[],"notExists":[]},"memo":""}],"order":2},{"id":"4a871b5c-18dd-4f9e-bbbe-aee8e29944d2","name":"C","color":"#FFFF8D","heros":[{"id":17,"ban":{"exists":[],"notExists":["6","5","8","7","4","3","2","1"]},"memo":"dddd"},{"id":7,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":12,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":13,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":26,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":28,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":40,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":47,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":52,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":59,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":60,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":71,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":74,"ban":{"exists":[],"notExists":[]},"memo":""}],"order":3},{"id":"0a2b5bad-f308-4beb-a342-d67829d08921","name":"D","color":"#CCFF90","heros":[{"id":10,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":8,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":19,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":18,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":25,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":33,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":42,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":48,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":54,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":61,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":64,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":69,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":73,"ban":{"exists":[],"notExists":[]},"memo":""}],"order":4}]',current_timestamp);
insert into TierTable values (10062, 'シェイミさんtier表',1,'[{"id":"f27ce896-790c-4b07-b278-7d68d6b1b046","name":"最強","color":"#FF8A80","heros":[{"id":27,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":20,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":69,"ban":{"exists":[],"notExists":[]},"memo":""}],"order":0},{"id":"6ba470de-5dc7-4c86-80cd-d5ee6e2c3b0e","name":"強い","color":"#FFA726","heros":[{"id":9,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":30,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":64,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":53,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":55,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":43,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":44,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":70,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":54,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":63,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":76,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":78,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":81,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":1,"ban":{"exists":[],"notExists":[]},"memo":""}],"order":1},{"id":"eb2bfbe5-64f0-48fd-a4a8-a34558d63c46","name":"普通","color":"#FFD180","heros":[{"id":49,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":31,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":33,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":58,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":37,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":39,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":40,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":36,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":26,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":73,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":7,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":29,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":10,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":48,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":45,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":24,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":42,"ban":{"exists":[],"notExists":[]},"memo":""}],"order":2},{"id":"b0d2cdee-3f17-4ffd-aa25-55f89eb16d56","name":"下位落ちする","color":"#FFFF8D","heros":[{"id":71,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":28,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":62,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":23,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":15,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":57,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":56,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":32,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":6,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":38,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":8,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":25,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":2,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":12,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":52,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":68,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":51,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":4,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":34,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":5,"ban":{"exists":[],"notExists":[]},"memo":""}],"order":3},{"id":"f6f3df25-8eb6-473f-a72f-b81e5d0357ad","name":"下位落ち濃厚","color":"#CCFF90","heros":[{"id":3,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":74,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":22,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":17,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":19,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":35,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":21,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":67,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":16,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":14,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":11,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":66,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":65,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":60,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":61,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":59,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":50,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":41,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":77,"ban":{"exists":[],"notExists":[]},"memo":""}],"order":4}]',current_timestamp);
insert into TierTable values (10063, 'test',1,'[{"id":"f15af68f-189f-42eb-912a-0e4537a03583","name":"S","color":"#FF8A80","heros":[{"id":74646,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":68129,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":77987,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":58534,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":61488,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":60212,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":58044,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":59203,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":57924,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":57929,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":60362,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":77516,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":60366,"ban":{"exists":[],"notExists":[]},"memo":""}],"order":0},{"id":"236eb83c-5a37-475c-a784-492f183b1f50","name":"A","color":"#FFA726","heros":[{"id":76562,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":59807,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":71458,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":57893,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":79615,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":58027,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":61489,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":70838,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":58435,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":60367,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":60370,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":60369,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":60372,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":73940,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":61910,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":71916,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":59397,"ban":{"exists":[],"notExists":[]},"memo":""}],"order":1},{"id":"df1080b0-12f2-4ec1-b63a-14a272fae350","name":"B","color":"#FFD180","heros":[{"id":66196,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":71454,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":60214,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":57634,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":57892,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":58024,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":66483,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":59831,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":82110,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":63319,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":57947,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":67553,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":71908,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":64485,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":58021,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":79719,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":64400,"ban":{"exists":[],"notExists":[]},"memo":""}],"order":2},{"id":"7cf44e1d-cc93-4f9d-9098-02d676d7a4a6","name":"C","color":"#FFFF8D","heros":[{"id":74631,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":59805,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":62242,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":57633,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":57891,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":58535,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":61490,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":62266,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":62268,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":61912,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":61914,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":64475,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":63601,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":80247,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":71463,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":60211,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":59806,"ban":{"exists":[],"notExists":[]},"memo":""}],"order":3},{"id":"091869cc-ea82-47c9-92da-cb0a4e9bd2d6","name":"D","color":"#CCFF90","heros":[{"id":64403,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":67356,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":81569,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":57635,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":59814,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":70956,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":57944,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":60213,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":64480,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":75702,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":57946,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":76521,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":63602,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":79618,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":80239,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":63604,"ban":{"exists":[],"notExists":[]},"memo":""},{"id":80832,"ban":{"exists":[],"notExists":[]},"memo":""}],"order":4}]',current_timestamp);
SELECT SETVAL ('heroid_seq', '100');

insert into MinderRanking values(1,'Jeef Curve','Warrior Curve','A. F. Kay','C');
insert into MinderRanking values(2,'Slow Rafaam Curve','Rafaam Curve','Akazamzarak','C');
insert into MinderRanking values(3,'3 on 3 ','Fast Basic Curve','Al Akir','C');
insert into MinderRanking values(4,'Fast Basic Curve','Slow Jeef Curve','Alexstrasza','C');
insert into MinderRanking values(5,'None','None','Aranna ','D');
insert into MinderRanking values(6,'Rafaam Curve','Fast Jeef Curve','Barov',' A+');
insert into MinderRanking values(7,'Fast Basic Curve','3 on 3 ','Blackthorn','C');
insert into MinderRanking values(8,'Warrior Curve','Basic Curve','Brann',' A+');
insert into MinderRanking values(9,'Basic Curve','Slow Jeef Curve','Bigglesworth','C');
insert into MinderRanking values(10,'Fast Basic Curve','Jeef Curve','Brukan','D');
insert into MinderRanking values(11,'Fast Basic Curve','Toki Curve','Cariel','D');
insert into MinderRanking values(12,'Warrior Curve','Slow Jeef Curve','Chenvaala','C');
insert into MinderRanking values(13,'3 on 3 ','Fast Basic Curve','Cookie','S');
insert into MinderRanking values(14,'Aggro Yogg Curve','None','Cthun','D');
insert into MinderRanking values(15,'Fast Basic Curve','Slow Jeef Curve','Curator','C');
insert into MinderRanking values(16,'Warrior Curve','None','Deathwing','D');
insert into MinderRanking values(17,'None','Slow Rafaam Curve','Deryl','C');
insert into MinderRanking values(18,'3 on 3 ','Fast Basic Curve','Drek''Thar','F');
insert into MinderRanking values(19,'Slow Rafaam Curve','Rafaam Curve','Edwin','D');
insert into MinderRanking values(20,'Fast Basic Curve','3 on 3 ','Elise','C');
insert into MinderRanking values(21,'Rafaam Curve','None','Eudora','C');
insert into MinderRanking values(22,'None','None','Finley',' A-');
insert into MinderRanking values(23,'Basic Curve','None','Flurgl','F');
insert into MinderRanking values(24,'Slow Rafaam Curve','Rafaam Curve','Galakrond','B');
insert into MinderRanking values(25,'3 on 3 ','None','Galewing',' A+');
insert into MinderRanking values(26,'Warrior Curve','None','Gallywix','S');
insert into MinderRanking values(27,'Basic Curve','Slow Jeef Curve','George','B');
insert into MinderRanking values(28,'Jeef Curve','3 on 3','Greybough','C');
insert into MinderRanking values(29,'None','None','Guff','F');
insert into MinderRanking values(30,'Jeef Curve','Warrior Curve','Hooktusk','S');
insert into MinderRanking values(31,'3 on 3 ','None','Illidan','D');
insert into MinderRanking values(32,'Slow Jeef Curve','Fast Basic Curve','Jandice','S');
insert into MinderRanking values(33,'Warrior Curve','Slow Rafaam Curve','Jaraxxus','D');
insert into MinderRanking values(34,'Basic Curve','Slow Jeef Curve','Kaelthas','C');
insert into MinderRanking values(35,'Fast Basic Curve','Slow Jeef Curve','Kragg','C');
insert into MinderRanking values(36,'Basic Curve','Slow Jeef Curve','Kurtrus','C');
insert into MinderRanking values(37,'Jeef Curve','3 on 3 ','Lich Bazhial',' A+');
insert into MinderRanking values(38,'3 on 3 ','Fast Basic Curve','Lich King','B');
insert into MinderRanking values(39,'Rafaam Curve','None','Maiev',' A+');
insert into MinderRanking values(40,'Warrior Curve','Jeef Curve','Malygos',' A-');
insert into MinderRanking values(41,'Slow Jeef Curve','Warrior Curve','Millhouse','B');
insert into MinderRanking values(42,'Warrior Curve','3 on 3 ','Millificent','D');
insert into MinderRanking values(43,'Rafaam Curve','Toki Curve','Mukla','C');
insert into MinderRanking values(44,'Jeef Curve','None','Mutanus',' A-');
insert into MinderRanking values(45,'3 on 3 ','Fast Basic Curve','Nguyen',' A+');
insert into MinderRanking values(46,'Fast Basic Curve','Slow Jeef Curve','Nozdormu','C');
insert into MinderRanking values(47,'Toki Curve','Warrior Curve','Nzoth','C');
insert into MinderRanking values(48,'Fast Basic Curve','Slow Jeef Curve','Omu',' A+');
insert into MinderRanking values(49,'Jeef Curve','Warrior Curve','Onyxia','D');
insert into MinderRanking values(50,'Toki Curve','Fast Basic Curve','Patches','C');
insert into MinderRanking values(51,'3 on 3 ','Fast Basic Curve','Patchwerk','C');
insert into MinderRanking values(52,'Rafaam Curve','None','Pyramad','D');
insert into MinderRanking values(53,'Rafaam Curve','None','Rafaam','S');
insert into MinderRanking values(54,'Slow Jeef Curve','Basic Curve','Ragnaros','D');
insert into MinderRanking values(55,'Fast Basic Curve','Slow Jeef Curve','Rakanishu','F');
insert into MinderRanking values(56,'Slow Jeef Curve','None','Rat King','D');
insert into MinderRanking values(57,'Warrior Curve','None','Reno Jackson',' A-');
insert into MinderRanking values(58,'Jeef Curve','Fast Basic Curve','Rokara','B');
insert into MinderRanking values(59,'Rafaam Curve','None','Saurfang','C');
insert into MinderRanking values(60,'Aggro Yogg Curve','Warrior Curve','Scabbs','S');
insert into MinderRanking values(61,'Warrior Curve','None','Shudderwock','S');
insert into MinderRanking values(62,'Fast Basic Curve','3 on 3 ','Silas',' A-');
insert into MinderRanking values(63,'Fast Basic Curve','None','Sindragosa','D');
insert into MinderRanking values(64,'Warrior Curve','None','Sneed','C');
insert into MinderRanking values(65,'Slow Jeef Curve','Fast Basic Curve','Tamsin','C');
insert into MinderRanking values(66,'Jeef Curve','Fast Basic Curve','Tavish Stormpike','D');
insert into MinderRanking values(67,'Warrior Curve','Slow Jeef Curve','Tess','B');
insert into MinderRanking values(68,'Fast Basic Curve','Slow Jeef Curve','Tickatus','B');
insert into MinderRanking values(69,'Toki Curve','Fast Basic Curve','Toki','C');
insert into MinderRanking values(70,'Slow Jeef Curve','None','Vanndar ','D');
insert into MinderRanking values(71,'Fast Basic Curve','None','Varden','B');
insert into MinderRanking values(72,'Warrior Curve','None','Voljin',' A+');
insert into MinderRanking values(73,'Rafaam Curve','None','Wagtoggle','D');
insert into MinderRanking values(74,'Aggro Yogg Curve','Basic Yogg Curve','Xyrella',' A+');
insert into MinderRanking values(75,'Aggro Yogg Curve','Basic Yogg Curve','Yogg','B');
insert into MinderRanking values(76,'Jeef Curve','None','Ysera','D');
insert into MinderRanking values(77,'Fast Basic Curve','Basic Yogg Curve','Yshaarj','B');
insert into MinderRanking values(78,'Fast Basic Curve','Slow Jeef Curve','Zephrys','B');
insert into MinderRanking values(79,'Fast Basic Curve','None','Ambassador Faelin',' A+');
insert into MinderRanking values(80,'Warrior Curve','None','Ini Stormcoil','F');

insert into MinderRankingDetail values(1,'Demons','Irrellevant',1);
insert into MinderRankingDetail values(2,'Dragons','Irrellevant',1);
insert into MinderRankingDetail values(3,'Pirates','Helpful',1);
insert into MinderRankingDetail values(4,'Quillboar','Helpful',1);
insert into MinderRankingDetail values(5,'Mechs','Helpful',1);
insert into MinderRankingDetail values(6,'Elementals','Irrellevant',1);
insert into MinderRankingDetail values(7,'Murlocs','Irrellevant',1);
insert into MinderRankingDetail values(8,'Beast','Irrellevant',1);
insert into MinderRankingDetail values(9,'Nagas','Irrellevant',1);
insert into MinderRankingDetail values(10,'Demons','Helpful',2);
insert into MinderRankingDetail values(11,'Dragons','Irrellevant',2);
insert into MinderRankingDetail values(12,'Pirates','Irrellevant',2);
insert into MinderRankingDetail values(13,'Quillboar','Irrellevant',2);
insert into MinderRankingDetail values(14,'Mechs','Helpful',2);
insert into MinderRankingDetail values(15,'Elementals','Irrellevant',2);
insert into MinderRankingDetail values(16,'Murlocs','Helpful',2);
insert into MinderRankingDetail values(17,'Beast','Irrellevant',2);
insert into MinderRankingDetail values(18,'Nagas','Avoid',2);
insert into MinderRankingDetail values(19,'Demons','Irrellevant',3);
insert into MinderRankingDetail values(20,'Dragons','Irrellevant',3);
insert into MinderRankingDetail values(21,'Pirates','Helpful',3);
insert into MinderRankingDetail values(22,'Quillboar','Helpful',3);
insert into MinderRankingDetail values(23,'Mechs','Irrellevant',3);
insert into MinderRankingDetail values(24,'Elementals','Irrellevant',3);
insert into MinderRankingDetail values(25,'Murlocs','Helpful',3);
insert into MinderRankingDetail values(26,'Beast','Irrellevant',3);
insert into MinderRankingDetail values(27,'Nagas','Irrellevant',3);
insert into MinderRankingDetail values(28,'Demons','Avoid',4);
insert into MinderRankingDetail values(29,'Dragons','Need',4);
insert into MinderRankingDetail values(30,'Pirates','Avoid',4);
insert into MinderRankingDetail values(31,'Quillboar','Irrellevant',4);
insert into MinderRankingDetail values(32,'Mechs','Irrellevant',4);
insert into MinderRankingDetail values(33,'Elementals','Irrellevant',4);
insert into MinderRankingDetail values(34,'Murlocs','Helpful',4);
insert into MinderRankingDetail values(35,'Beast','Irrellevant',4);
insert into MinderRankingDetail values(36,'Nagas','Avoid',4);
insert into MinderRankingDetail values(37,'Demons','Irrellevant',5);
insert into MinderRankingDetail values(38,'Dragons','Irrellevant',5);
insert into MinderRankingDetail values(39,'Pirates','Irrellevant',5);
insert into MinderRankingDetail values(40,'Quillboar','Irrellevant',5);
insert into MinderRankingDetail values(41,'Mechs','Avoid',5);
insert into MinderRankingDetail values(42,'Elementals','Helpful',5);
insert into MinderRankingDetail values(43,'Murlocs','Helpful',5);
insert into MinderRankingDetail values(44,'Beast','Irrellevant',5);
insert into MinderRankingDetail values(45,'Nagas','Avoid',5);
insert into MinderRankingDetail values(46,'Demons','Avoid',6);
insert into MinderRankingDetail values(47,'Dragons','Avoid',6);
insert into MinderRankingDetail values(48,'Pirates','Helpful',6);
insert into MinderRankingDetail values(49,'Quillboar','Helpful',6);
insert into MinderRankingDetail values(50,'Mechs','Helpful',6);
insert into MinderRankingDetail values(51,'Elementals','Irrellevant',6);
insert into MinderRankingDetail values(52,'Murlocs','Irrellevant',6);
insert into MinderRankingDetail values(53,'Beast','Irrellevant',6);
insert into MinderRankingDetail values(54,'Nagas','Helpful',6);
insert into MinderRankingDetail values(55,'Demons','Irrellevant',7);
insert into MinderRankingDetail values(56,'Dragons','Helpful',7);
insert into MinderRankingDetail values(57,'Pirates','Irrellevant',7);
insert into MinderRankingDetail values(58,'Quillboar','Need',7);
insert into MinderRankingDetail values(59,'Mechs','Helpful',7);
insert into MinderRankingDetail values(60,'Elementals','Irrellevant',7);
insert into MinderRankingDetail values(61,'Murlocs','Irrellevant',7);
insert into MinderRankingDetail values(62,'Beast','Irrellevant',7);
insert into MinderRankingDetail values(63,'Nagas','Helpful',7);
insert into MinderRankingDetail values(64,'Demons','Avoid',8);
insert into MinderRankingDetail values(65,'Dragons','Irrellevant',8);
insert into MinderRankingDetail values(66,'Pirates','Irrellevant',8);
insert into MinderRankingDetail values(67,'Quillboar','Helpful',8);
insert into MinderRankingDetail values(68,'Mechs','Avoid',8);
insert into MinderRankingDetail values(69,'Elementals','Helpful',8);
insert into MinderRankingDetail values(70,'Murlocs','Helpful',8);
insert into MinderRankingDetail values(71,'Beast','Helpful',8);
insert into MinderRankingDetail values(72,'Nagas','Helpful',8);
insert into MinderRankingDetail values(73,'Demons','Irrellevant',9);
insert into MinderRankingDetail values(74,'Dragons','Irrellevant',9);
insert into MinderRankingDetail values(75,'Pirates','Irrellevant',9);
insert into MinderRankingDetail values(76,'Quillboar','Helpful',9);
insert into MinderRankingDetail values(77,'Mechs','Avoid',9);
insert into MinderRankingDetail values(78,'Elementals','Irrellevant',9);
insert into MinderRankingDetail values(79,'Murlocs','Helpful',9);
insert into MinderRankingDetail values(80,'Beast','Helpful',9);
insert into MinderRankingDetail values(81,'Nagas','Helpful',9);
insert into MinderRankingDetail values(82,'Demons','Irrellevant',10);
insert into MinderRankingDetail values(83,'Dragons','Irrellevant',10);
insert into MinderRankingDetail values(84,'Pirates','Irrellevant',10);
insert into MinderRankingDetail values(85,'Quillboar','Irrellevant',10);
insert into MinderRankingDetail values(86,'Mechs','Helpful',10);
insert into MinderRankingDetail values(87,'Elementals','Irrellevant',10);
insert into MinderRankingDetail values(88,'Murlocs','Helpful',10);
insert into MinderRankingDetail values(89,'Beast','Irrellevant',10);
insert into MinderRankingDetail values(90,'Nagas','Irrellevant',10);
insert into MinderRankingDetail values(91,'Demons','Irrellevant',11);
insert into MinderRankingDetail values(92,'Dragons','Helpful',11);
insert into MinderRankingDetail values(93,'Pirates','Irrellevant',11);
insert into MinderRankingDetail values(94,'Quillboar','Helpful',11);
insert into MinderRankingDetail values(95,'Mechs','Helpful',11);
insert into MinderRankingDetail values(96,'Elementals','Helpful',11);
insert into MinderRankingDetail values(97,'Murlocs','Irrellevant',11);
insert into MinderRankingDetail values(98,'Beast','Irrellevant',11);
insert into MinderRankingDetail values(99,'Nagas','Avoid',11);
insert into MinderRankingDetail values(100,'Demons','Avoid',12);
insert into MinderRankingDetail values(101,'Dragons','Irrellevant',12);
insert into MinderRankingDetail values(102,'Pirates','Irrellevant',12);
insert into MinderRankingDetail values(103,'Quillboar','Irrellevant',12);
insert into MinderRankingDetail values(104,'Mechs','Avoid',12);
insert into MinderRankingDetail values(105,'Elementals','Need',12);
insert into MinderRankingDetail values(106,'Murlocs','Irrellevant',12);
insert into MinderRankingDetail values(107,'Beast','Avoid',12);
insert into MinderRankingDetail values(108,'Nagas','Irrellevant',12);
insert into MinderRankingDetail values(109,'Demons','Avoid',13);
insert into MinderRankingDetail values(110,'Dragons','Irrellevant',13);
insert into MinderRankingDetail values(111,'Pirates','Helpful',13);
insert into MinderRankingDetail values(112,'Quillboar','Helpful',13);
insert into MinderRankingDetail values(113,'Mechs','Irrellevant',13);
insert into MinderRankingDetail values(114,'Elementals','Irrellevant',13);
insert into MinderRankingDetail values(115,'Murlocs','Helpful',13);
insert into MinderRankingDetail values(116,'Beast','Avoid',13);
insert into MinderRankingDetail values(117,'Nagas','Helpful',13);
insert into MinderRankingDetail values(118,'Demons','Irrellevant',14);
insert into MinderRankingDetail values(119,'Dragons','Helpful',14);
insert into MinderRankingDetail values(120,'Pirates','Irrellevant',14);
insert into MinderRankingDetail values(121,'Quillboar','Irrellevant',14);
insert into MinderRankingDetail values(122,'Mechs','Helpful',14);
insert into MinderRankingDetail values(123,'Elementals','Helpful',14);
insert into MinderRankingDetail values(124,'Murlocs','Irrellevant',14);
insert into MinderRankingDetail values(125,'Beast','Irrellevant',14);
insert into MinderRankingDetail values(126,'Nagas','Unplayable',14);
insert into MinderRankingDetail values(127,'Demons','Irrellevant',15);
insert into MinderRankingDetail values(128,'Dragons','Irrellevant',15);
insert into MinderRankingDetail values(129,'Pirates','Irrellevant',15);
insert into MinderRankingDetail values(130,'Quillboar','Helpful',15);
insert into MinderRankingDetail values(131,'Mechs','Helpful',15);
insert into MinderRankingDetail values(132,'Elementals','Helpful',15);
insert into MinderRankingDetail values(133,'Murlocs','Helpful',15);
insert into MinderRankingDetail values(134,'Beast','Avoid',15);
insert into MinderRankingDetail values(135,'Nagas','Avoid',15);
insert into MinderRankingDetail values(136,'Demons','Helpful',16);
insert into MinderRankingDetail values(137,'Dragons','Irrellevant',16);
insert into MinderRankingDetail values(138,'Pirates','Helpful',16);
insert into MinderRankingDetail values(139,'Quillboar','Irrellevant',16);
insert into MinderRankingDetail values(140,'Mechs','Helpful',16);
insert into MinderRankingDetail values(141,'Elementals','Irrellevant',16);
insert into MinderRankingDetail values(142,'Murlocs','Irrellevant',16);
insert into MinderRankingDetail values(143,'Beast','Helpful',16);
insert into MinderRankingDetail values(144,'Nagas','Avoid',16);
insert into MinderRankingDetail values(145,'Demons','Helpful',17);
insert into MinderRankingDetail values(146,'Dragons','Irrellevant',17);
insert into MinderRankingDetail values(147,'Pirates','Irrellevant',17);
insert into MinderRankingDetail values(148,'Quillboar','Irrellevant',17);
insert into MinderRankingDetail values(149,'Mechs','Helpful',17);
insert into MinderRankingDetail values(150,'Elementals','Helpful',17);
insert into MinderRankingDetail values(151,'Murlocs','Irrellevant',17);
insert into MinderRankingDetail values(152,'Beast','Irrellevant',17);
insert into MinderRankingDetail values(153,'Nagas','Avoid',17);
insert into MinderRankingDetail values(154,'Demons','Irrellevant',18);
insert into MinderRankingDetail values(155,'Dragons','Irrellevant',18);
insert into MinderRankingDetail values(156,'Pirates','Irrellevant',18);
insert into MinderRankingDetail values(157,'Quillboar','Helpful',18);
insert into MinderRankingDetail values(158,'Mechs','Helpful',18);
insert into MinderRankingDetail values(159,'Elementals','Irrellevant',18);
insert into MinderRankingDetail values(160,'Murlocs','Irrellevant',18);
insert into MinderRankingDetail values(161,'Beast','Helpful',18);
insert into MinderRankingDetail values(162,'Nagas','Avoid',18);
insert into MinderRankingDetail values(163,'Demons','Irrellevant',19);
insert into MinderRankingDetail values(164,'Dragons','Irrellevant',19);
insert into MinderRankingDetail values(165,'Pirates','Helpful',19);
insert into MinderRankingDetail values(166,'Quillboar','Helpful',19);
insert into MinderRankingDetail values(167,'Mechs','Helpful',19);
insert into MinderRankingDetail values(168,'Elementals','Irrellevant',19);
insert into MinderRankingDetail values(169,'Murlocs','Irrellevant',19);
insert into MinderRankingDetail values(170,'Beast','Irrellevant',19);
insert into MinderRankingDetail values(171,'Nagas','Avoid',19);
insert into MinderRankingDetail values(172,'Demons','Irrellevant',20);
insert into MinderRankingDetail values(173,'Dragons','Irrellevant',20);
insert into MinderRankingDetail values(174,'Pirates','Helpful',20);
insert into MinderRankingDetail values(175,'Quillboar','Helpful',20);
insert into MinderRankingDetail values(176,'Mechs','Irrellevant',20);
insert into MinderRankingDetail values(177,'Elementals','Irrellevant',20);
insert into MinderRankingDetail values(178,'Murlocs','Helpful',20);
insert into MinderRankingDetail values(179,'Beast','Irrellevant',20);
insert into MinderRankingDetail values(180,'Nagas','Helpful',20);
insert into MinderRankingDetail values(181,'Demons','Avoid',21);
insert into MinderRankingDetail values(182,'Dragons','Avoid',21);
insert into MinderRankingDetail values(183,'Pirates','Helpful',21);
insert into MinderRankingDetail values(184,'Quillboar','Helpful',21);
insert into MinderRankingDetail values(185,'Mechs','Irrellevant',21);
insert into MinderRankingDetail values(186,'Elementals','Irrellevant',21);
insert into MinderRankingDetail values(187,'Murlocs','Irrellevant',21);
insert into MinderRankingDetail values(188,'Beast','Irrellevant',21);
insert into MinderRankingDetail values(189,'Nagas','Helpful',21);
insert into MinderRankingDetail values(190,'Demons','Irrellevant',22);
insert into MinderRankingDetail values(191,'Dragons','Irrellevant',22);
insert into MinderRankingDetail values(192,'Pirates','Irrellevant',22);
insert into MinderRankingDetail values(193,'Quillboar','Helpful',22);
insert into MinderRankingDetail values(194,'Mechs','Irrellevant',22);
insert into MinderRankingDetail values(195,'Elementals','Irrellevant',22);
insert into MinderRankingDetail values(196,'Murlocs','Helpful',22);
insert into MinderRankingDetail values(197,'Beast','Irrellevant',22);
insert into MinderRankingDetail values(198,'Nagas','Irrellevant',22);
insert into MinderRankingDetail values(199,'Demons','Irrellevant',23);
insert into MinderRankingDetail values(200,'Dragons','Irrellevant',23);
insert into MinderRankingDetail values(201,'Pirates','Irrellevant',23);
insert into MinderRankingDetail values(202,'Quillboar','Irrellevant',23);
insert into MinderRankingDetail values(203,'Mechs','Irrellevant',23);
insert into MinderRankingDetail values(204,'Elementals','Irrellevant',23);
insert into MinderRankingDetail values(205,'Murlocs','Need',23);
insert into MinderRankingDetail values(206,'Beast','Irrellevant',23);
insert into MinderRankingDetail values(207,'Nagas','Avoid',23);
insert into MinderRankingDetail values(208,'Demons','Irrellevant',24);
insert into MinderRankingDetail values(209,'Dragons','Avoid',24);
insert into MinderRankingDetail values(210,'Pirates','Helpful',24);
insert into MinderRankingDetail values(211,'Quillboar','Helpful',24);
insert into MinderRankingDetail values(212,'Mechs','Irrellevant',24);
insert into MinderRankingDetail values(213,'Elementals','Irrellevant',24);
insert into MinderRankingDetail values(214,'Murlocs','Irrellevant',24);
insert into MinderRankingDetail values(215,'Beast','Helpful',24);
insert into MinderRankingDetail values(216,'Nagas','Helpful',24);
insert into MinderRankingDetail values(217,'Demons','Avoid',25);
insert into MinderRankingDetail values(218,'Dragons','Irrellevant',25);
insert into MinderRankingDetail values(219,'Pirates','Helpful',25);
insert into MinderRankingDetail values(220,'Quillboar','Helpful',25);
insert into MinderRankingDetail values(221,'Mechs','Helpful',25);
insert into MinderRankingDetail values(222,'Elementals','Irrellevant',25);
insert into MinderRankingDetail values(223,'Murlocs','Irrellevant',25);
insert into MinderRankingDetail values(224,'Beast','Irrellevant',25);
insert into MinderRankingDetail values(225,'Nagas','Helpful',25);
insert into MinderRankingDetail values(226,'Demons','Avoid',26);
insert into MinderRankingDetail values(227,'Dragons','Irrellevant',26);
insert into MinderRankingDetail values(228,'Pirates','Helpful',26);
insert into MinderRankingDetail values(229,'Quillboar','Irrellevant',26);
insert into MinderRankingDetail values(230,'Mechs','Avoid',26);
insert into MinderRankingDetail values(231,'Elementals','Helpful',26);
insert into MinderRankingDetail values(232,'Murlocs','Helpful',26);
insert into MinderRankingDetail values(233,'Beast','Helpful',26);
insert into MinderRankingDetail values(234,'Nagas','Avoid',26);
insert into MinderRankingDetail values(235,'Demons','Irrellevant',27);
insert into MinderRankingDetail values(236,'Dragons','Helpful',27);
insert into MinderRankingDetail values(237,'Pirates','Irrellevant',27);
insert into MinderRankingDetail values(238,'Quillboar','Helpful',27);
insert into MinderRankingDetail values(239,'Mechs','Helpful',27);
insert into MinderRankingDetail values(240,'Elementals','Irrellevant',27);
insert into MinderRankingDetail values(241,'Murlocs','Helpful',27);
insert into MinderRankingDetail values(242,'Beast','Irrellevant',27);
insert into MinderRankingDetail values(243,'Nagas','Avoid',27);
insert into MinderRankingDetail values(244,'Demons','Helpful',28);
insert into MinderRankingDetail values(245,'Dragons','Irrellevant',28);
insert into MinderRankingDetail values(246,'Pirates','Irrellevant',28);
insert into MinderRankingDetail values(247,'Quillboar','Irrellevant',28);
insert into MinderRankingDetail values(248,'Mechs','Helpful',28);
insert into MinderRankingDetail values(249,'Elementals','Irrellevant',28);
insert into MinderRankingDetail values(250,'Murlocs','Irrellevant',28);
insert into MinderRankingDetail values(251,'Beast','Helpful',28);
insert into MinderRankingDetail values(252,'Nagas','Avoid',28);
insert into MinderRankingDetail values(253,'Demons','Irrellevant',29);
insert into MinderRankingDetail values(254,'Dragons','Irrellevant',29);
insert into MinderRankingDetail values(255,'Pirates','Irrellevant',29);
insert into MinderRankingDetail values(256,'Quillboar','Irrellevant',29);
insert into MinderRankingDetail values(257,'Mechs','Irrellevant',29);
insert into MinderRankingDetail values(258,'Elementals','Irrellevant',29);
insert into MinderRankingDetail values(259,'Murlocs','Irrellevant',29);
insert into MinderRankingDetail values(260,'Beast','Irrellevant',29);
insert into MinderRankingDetail values(261,'Nagas','Irrellevant',29);
insert into MinderRankingDetail values(262,'Demons','Irrellevant',30);
insert into MinderRankingDetail values(263,'Dragons','Avoid',30);
insert into MinderRankingDetail values(264,'Pirates','Helpful',30);
insert into MinderRankingDetail values(265,'Quillboar','Helpful',30);
insert into MinderRankingDetail values(266,'Mechs','Irrellevant',30);
insert into MinderRankingDetail values(267,'Elementals','Helpful',30);
insert into MinderRankingDetail values(268,'Murlocs','Irrellevant',30);
insert into MinderRankingDetail values(269,'Beast','Helpful',30);
insert into MinderRankingDetail values(270,'Nagas','Helpful',30);
insert into MinderRankingDetail values(271,'Demons','Avoid',31);
insert into MinderRankingDetail values(272,'Dragons','Irrellevant',31);
insert into MinderRankingDetail values(273,'Pirates','Helpful',31);
insert into MinderRankingDetail values(274,'Quillboar','Helpful',31);
insert into MinderRankingDetail values(275,'Mechs','Helpful',31);
insert into MinderRankingDetail values(276,'Elementals','Irrellevant',31);
insert into MinderRankingDetail values(277,'Murlocs','Irrellevant',31);
insert into MinderRankingDetail values(278,'Beast','Irrellevant',31);
insert into MinderRankingDetail values(279,'Nagas','Irrellevant',31);
insert into MinderRankingDetail values(280,'Demons','Irrellevant',32);
insert into MinderRankingDetail values(281,'Dragons','Irrellevant',32);
insert into MinderRankingDetail values(282,'Pirates','Helpful',32);
insert into MinderRankingDetail values(283,'Quillboar','Helpful',32);
insert into MinderRankingDetail values(284,'Mechs','Avoid',32);
insert into MinderRankingDetail values(285,'Elementals','Helpful',32);
insert into MinderRankingDetail values(286,'Murlocs','Helpful',32);
insert into MinderRankingDetail values(287,'Beast','Helpful',32);
insert into MinderRankingDetail values(288,'Nagas','Irrellevant',32);
insert into MinderRankingDetail values(289,'Demons','Need',33);
insert into MinderRankingDetail values(290,'Dragons','Irrellevant',33);
insert into MinderRankingDetail values(291,'Pirates','Irrellevant',33);
insert into MinderRankingDetail values(292,'Quillboar','Irrellevant',33);
insert into MinderRankingDetail values(293,'Mechs','Avoid',33);
insert into MinderRankingDetail values(294,'Elementals','Irrellevant',33);
insert into MinderRankingDetail values(295,'Murlocs','Avoid',33);
insert into MinderRankingDetail values(296,'Beast','Irrellevant',33);
insert into MinderRankingDetail values(297,'Nagas','Avoid',33);
insert into MinderRankingDetail values(298,'Demons','Irrellevant',34);
insert into MinderRankingDetail values(299,'Dragons','Irrellevant',34);
insert into MinderRankingDetail values(300,'Pirates','Helpful',34);
insert into MinderRankingDetail values(301,'Quillboar','Helpful',34);
insert into MinderRankingDetail values(302,'Mechs','Need',34);
insert into MinderRankingDetail values(303,'Elementals','Irrellevant',34);
insert into MinderRankingDetail values(304,'Murlocs','Irrellevant',34);
insert into MinderRankingDetail values(305,'Beast','Irrellevant',34);
insert into MinderRankingDetail values(306,'Nagas','Avoid',34);
insert into MinderRankingDetail values(307,'Demons','Irrellevant',35);
insert into MinderRankingDetail values(308,'Dragons','Irrellevant',35);
insert into MinderRankingDetail values(309,'Pirates','Helpful',35);
insert into MinderRankingDetail values(310,'Quillboar','Helpful',35);
insert into MinderRankingDetail values(311,'Mechs','Irrellevant',35);
insert into MinderRankingDetail values(312,'Elementals','Irrellevant',35);
insert into MinderRankingDetail values(313,'Murlocs','Helpful',35);
insert into MinderRankingDetail values(314,'Beast','Irrellevant',35);
insert into MinderRankingDetail values(315,'Nagas','Helpful',35);
insert into MinderRankingDetail values(316,'Demons','Helpful',36);
insert into MinderRankingDetail values(317,'Dragons','Irrellevant',36);
insert into MinderRankingDetail values(318,'Pirates','Avoid',36);
insert into MinderRankingDetail values(319,'Quillboar','Helpful',36);
insert into MinderRankingDetail values(320,'Mechs','Helpful',36);
insert into MinderRankingDetail values(321,'Elementals','Irrellevant',36);
insert into MinderRankingDetail values(322,'Murlocs','Irrellevant',36);
insert into MinderRankingDetail values(323,'Beast','Helpful',36);
insert into MinderRankingDetail values(324,'Nagas','Avoid',36);
insert into MinderRankingDetail values(325,'Demons','Irrellevant',37);
insert into MinderRankingDetail values(326,'Dragons','Irrellevant',37);
insert into MinderRankingDetail values(327,'Pirates','Irrellevant',37);
insert into MinderRankingDetail values(328,'Quillboar','Helpful',37);
insert into MinderRankingDetail values(329,'Mechs','Helpful',37);
insert into MinderRankingDetail values(330,'Elementals','Irrellevant',37);
insert into MinderRankingDetail values(331,'Murlocs','Helpful',37);
insert into MinderRankingDetail values(332,'Beast','Irrellevant',37);
insert into MinderRankingDetail values(333,'Nagas','Helpful',37);
insert into MinderRankingDetail values(334,'Demons','Irrellevant',38);
insert into MinderRankingDetail values(335,'Dragons','Irrellevant',38);
insert into MinderRankingDetail values(336,'Pirates','Irrellevant',38);
insert into MinderRankingDetail values(337,'Quillboar','Irrellevant',38);
insert into MinderRankingDetail values(338,'Mechs','Helpful',38);
insert into MinderRankingDetail values(339,'Elementals','Irrellevant',38);
insert into MinderRankingDetail values(340,'Murlocs','Helpful',38);
insert into MinderRankingDetail values(341,'Beast','Need',38);
insert into MinderRankingDetail values(342,'Nagas','Irrellevant',38);
insert into MinderRankingDetail values(343,'Demons','Irrellevant',39);
insert into MinderRankingDetail values(344,'Dragons','Avoid',39);
insert into MinderRankingDetail values(345,'Pirates','Helpful',39);
insert into MinderRankingDetail values(346,'Quillboar','Helpful',39);
insert into MinderRankingDetail values(347,'Mechs','Helpful',39);
insert into MinderRankingDetail values(348,'Elementals','Irrellevant',39);
insert into MinderRankingDetail values(349,'Murlocs','Helpful',39);
insert into MinderRankingDetail values(350,'Beast','Irrellevant',39);
insert into MinderRankingDetail values(351,'Nagas','Helpful',39);
insert into MinderRankingDetail values(352,'Demons','Irrellevant',40);
insert into MinderRankingDetail values(353,'Dragons','Irrellevant',40);
insert into MinderRankingDetail values(354,'Pirates','Helpful',40);
insert into MinderRankingDetail values(355,'Quillboar','Helpful',40);
insert into MinderRankingDetail values(356,'Mechs','Irrellevant',40);
insert into MinderRankingDetail values(357,'Elementals','Helpful',40);
insert into MinderRankingDetail values(358,'Murlocs','Irrellevant',40);
insert into MinderRankingDetail values(359,'Beast','Helpful',40);
insert into MinderRankingDetail values(360,'Nagas','Irrellevant',40);
insert into MinderRankingDetail values(361,'Demons','Irrellevant',41);
insert into MinderRankingDetail values(362,'Dragons','Irrellevant',41);
insert into MinderRankingDetail values(363,'Pirates','Helpful',41);
insert into MinderRankingDetail values(364,'Quillboar','Helpful',41);
insert into MinderRankingDetail values(365,'Mechs','Avoid',41);
insert into MinderRankingDetail values(366,'Elementals','Helpful',41);
insert into MinderRankingDetail values(367,'Murlocs','Irrellevant',41);
insert into MinderRankingDetail values(368,'Beast','Irrellevant',41);
insert into MinderRankingDetail values(369,'Nagas','Avoid',41);
insert into MinderRankingDetail values(370,'Demons','Irrellevant',42);
insert into MinderRankingDetail values(371,'Dragons','Avoid',42);
insert into MinderRankingDetail values(372,'Pirates','Irrellevant',42);
insert into MinderRankingDetail values(373,'Quillboar','Irrellevant',42);
insert into MinderRankingDetail values(374,'Mechs','Need',42);
insert into MinderRankingDetail values(375,'Elementals','Irrellevant',42);
insert into MinderRankingDetail values(376,'Murlocs','Irrellevant',42);
insert into MinderRankingDetail values(377,'Beast','Irrellevant',42);
insert into MinderRankingDetail values(378,'Nagas','Irrellevant',42);
insert into MinderRankingDetail values(379,'Demons','Helpful',43);
insert into MinderRankingDetail values(380,'Dragons','Helpful',43);
insert into MinderRankingDetail values(381,'Pirates','Irrellevant',43);
insert into MinderRankingDetail values(382,'Quillboar','Irrellevant',43);
insert into MinderRankingDetail values(383,'Mechs','Helpful',43);
insert into MinderRankingDetail values(384,'Elementals','Irrellevant',43);
insert into MinderRankingDetail values(385,'Murlocs','Irrellevant',43);
insert into MinderRankingDetail values(386,'Beast','Irrellevant',43);
insert into MinderRankingDetail values(387,'Nagas','Avoid',43);
insert into MinderRankingDetail values(388,'Demons','Avoid',44);
insert into MinderRankingDetail values(389,'Dragons','Helpful',44);
insert into MinderRankingDetail values(390,'Pirates','Irrellevant',44);
insert into MinderRankingDetail values(391,'Quillboar','Helpful',44);
insert into MinderRankingDetail values(392,'Mechs','Helpful',44);
insert into MinderRankingDetail values(393,'Elementals','Irrellevant',44);
insert into MinderRankingDetail values(394,'Murlocs','Avoid',44);
insert into MinderRankingDetail values(395,'Beast','Irrellevant',44);
insert into MinderRankingDetail values(396,'Nagas','Helpful',44);
insert into MinderRankingDetail values(397,'Demons','Irrellevant',45);
insert into MinderRankingDetail values(398,'Dragons','Irrellevant',45);
insert into MinderRankingDetail values(399,'Pirates','Irrellevant',45);
insert into MinderRankingDetail values(400,'Quillboar','Irrellevant',45);
insert into MinderRankingDetail values(401,'Mechs','Helpful',45);
insert into MinderRankingDetail values(402,'Elementals','Irrellevant',45);
insert into MinderRankingDetail values(403,'Murlocs','Helpful',45);
insert into MinderRankingDetail values(404,'Beast','Irrellevant',45);
insert into MinderRankingDetail values(405,'Nagas','Irrellevant',45);
insert into MinderRankingDetail values(406,'Demons','Irrellevant',46);
insert into MinderRankingDetail values(407,'Dragons','Irrellevant',46);
insert into MinderRankingDetail values(408,'Pirates','Helpful',46);
insert into MinderRankingDetail values(409,'Quillboar','Helpful',46);
insert into MinderRankingDetail values(410,'Mechs','Helpful',46);
insert into MinderRankingDetail values(411,'Elementals','Irrellevant',46);
insert into MinderRankingDetail values(412,'Murlocs','Irrellevant',46);
insert into MinderRankingDetail values(413,'Beast','Irrellevant',46);
insert into MinderRankingDetail values(414,'Nagas','Irrellevant',46);
insert into MinderRankingDetail values(415,'Demons','Irrellevant',47);
insert into MinderRankingDetail values(416,'Dragons','Irrellevant',47);
insert into MinderRankingDetail values(417,'Pirates','Irrellevant',47);
insert into MinderRankingDetail values(418,'Quillboar','Irrellevant',47);
insert into MinderRankingDetail values(419,'Mechs','Helpful',47);
insert into MinderRankingDetail values(420,'Elementals','Irrellevant',47);
insert into MinderRankingDetail values(421,'Murlocs','Irrellevant',47);
insert into MinderRankingDetail values(422,'Beast','Helpful',47);
insert into MinderRankingDetail values(423,'Nagas','Irrellevant',47);
insert into MinderRankingDetail values(424,'Demons','Irrellevant',48);
insert into MinderRankingDetail values(425,'Dragons','Irrellevant',48);
insert into MinderRankingDetail values(426,'Pirates','Helpful',48);
insert into MinderRankingDetail values(427,'Quillboar','Helpful',48);
insert into MinderRankingDetail values(428,'Mechs','Irrellevant',48);
insert into MinderRankingDetail values(429,'Elementals','Helpful',48);
insert into MinderRankingDetail values(430,'Murlocs','Irrellevant',48);
insert into MinderRankingDetail values(431,'Beast','Irrellevant',48);
insert into MinderRankingDetail values(432,'Nagas','Helpful',48);
insert into MinderRankingDetail values(433,'Demons','Helpful',49);
insert into MinderRankingDetail values(434,'Dragons','Irrellevant',49);
insert into MinderRankingDetail values(435,'Pirates','Irrellevant',49);
insert into MinderRankingDetail values(436,'Quillboar','Irrellevant',49);
insert into MinderRankingDetail values(437,'Mechs','Helpful',49);
insert into MinderRankingDetail values(438,'Elementals','Irrellevant',49);
insert into MinderRankingDetail values(439,'Murlocs','Irrellevant',49);
insert into MinderRankingDetail values(440,'Beast','Helpful',49);
insert into MinderRankingDetail values(441,'Nagas','Avoid',49);
insert into MinderRankingDetail values(442,'Demons','Irrellevant',50);
insert into MinderRankingDetail values(443,'Dragons','Irrellevant',50);
insert into MinderRankingDetail values(444,'Pirates','Need',50);
insert into MinderRankingDetail values(445,'Quillboar','Irrellevant',50);
insert into MinderRankingDetail values(446,'Mechs','Avoid',50);
insert into MinderRankingDetail values(447,'Elementals','Irrellevant',50);
insert into MinderRankingDetail values(448,'Murlocs','Avoid',50);
insert into MinderRankingDetail values(449,'Beast','Irrellevant',50);
insert into MinderRankingDetail values(450,'Nagas','Avoid',50);
insert into MinderRankingDetail values(451,'Demons','Irrellevant',51);
insert into MinderRankingDetail values(452,'Dragons','Irrellevant',51);
insert into MinderRankingDetail values(453,'Pirates','Helpful',51);
insert into MinderRankingDetail values(454,'Quillboar','Helpful',51);
insert into MinderRankingDetail values(455,'Mechs','Helpful',51);
insert into MinderRankingDetail values(456,'Elementals','Irrellevant',51);
insert into MinderRankingDetail values(457,'Murlocs','Irrellevant',51);
insert into MinderRankingDetail values(458,'Beast','Irrellevant',51);
insert into MinderRankingDetail values(459,'Nagas','Avoid',51);
insert into MinderRankingDetail values(460,'Demons','Helpful',52);
insert into MinderRankingDetail values(461,'Dragons','Irrellevant',52);
insert into MinderRankingDetail values(462,'Pirates','Irrellevant',52);
insert into MinderRankingDetail values(463,'Quillboar','Irrellevant',52);
insert into MinderRankingDetail values(464,'Mechs','Avoid',52);
insert into MinderRankingDetail values(465,'Elementals','Irrellevant',52);
insert into MinderRankingDetail values(466,'Murlocs','Helpful',52);
insert into MinderRankingDetail values(467,'Beast','Irrellevant',52);
insert into MinderRankingDetail values(468,'Nagas','Avoid',52);
insert into MinderRankingDetail values(469,'Demons','Irrellevant',53);
insert into MinderRankingDetail values(470,'Dragons','Irrellevant',53);
insert into MinderRankingDetail values(471,'Pirates','Helpful',53);
insert into MinderRankingDetail values(472,'Quillboar','Helpful',53);
insert into MinderRankingDetail values(473,'Mechs','Irrellevant',53);
insert into MinderRankingDetail values(474,'Elementals','Irrellevant',53);
insert into MinderRankingDetail values(475,'Murlocs','Helpful',53);
insert into MinderRankingDetail values(476,'Beast','Avoid',53);
insert into MinderRankingDetail values(477,'Nagas','Helpful',53);
insert into MinderRankingDetail values(478,'Demons','Need',54);
insert into MinderRankingDetail values(479,'Dragons','Irrellevant',54);
insert into MinderRankingDetail values(480,'Pirates','Irrellevant',54);
insert into MinderRankingDetail values(481,'Quillboar','Helpful',54);
insert into MinderRankingDetail values(482,'Mechs','Helpful',54);
insert into MinderRankingDetail values(483,'Elementals','Irrellevant',54);
insert into MinderRankingDetail values(484,'Murlocs','Irrellevant',54);
insert into MinderRankingDetail values(485,'Beast','Irrellevant',54);
insert into MinderRankingDetail values(486,'Nagas','Avoid',54);
insert into MinderRankingDetail values(487,'Demons','Irrellevant',55);
insert into MinderRankingDetail values(488,'Dragons','Irrellevant',55);
insert into MinderRankingDetail values(489,'Pirates','Irrellevant',55);
insert into MinderRankingDetail values(490,'Quillboar','Irrellevant',55);
insert into MinderRankingDetail values(491,'Mechs','Helpful',55);
insert into MinderRankingDetail values(492,'Elementals','Irrellevant',55);
insert into MinderRankingDetail values(493,'Murlocs','Irrellevant',55);
insert into MinderRankingDetail values(494,'Beast','Helpful',55);
insert into MinderRankingDetail values(495,'Nagas','Irrellevant',55);
insert into MinderRankingDetail values(496,'Demons','Irrellevant',56);
insert into MinderRankingDetail values(497,'Dragons','Helpful',56);
insert into MinderRankingDetail values(498,'Pirates','Irrellevant',56);
insert into MinderRankingDetail values(499,'Quillboar','Irrellevant',56);
insert into MinderRankingDetail values(500,'Mechs','Helpful',56);
insert into MinderRankingDetail values(501,'Elementals','Helpful',56);
insert into MinderRankingDetail values(502,'Murlocs','Helpful',56);
insert into MinderRankingDetail values(503,'Beast','Irrellevant',56);
insert into MinderRankingDetail values(504,'Nagas','Avoid',56);
insert into MinderRankingDetail values(505,'Demons','Irrellevant',57);
insert into MinderRankingDetail values(506,'Dragons','Irrellevant',57);
insert into MinderRankingDetail values(507,'Pirates','Helpful',57);
insert into MinderRankingDetail values(508,'Quillboar','Helpful',57);
insert into MinderRankingDetail values(509,'Mechs','Irrellevant',57);
insert into MinderRankingDetail values(510,'Elementals','Irrellevant',57);
insert into MinderRankingDetail values(511,'Murlocs','Helpful',57);
insert into MinderRankingDetail values(512,'Beast','Helpful',57);
insert into MinderRankingDetail values(513,'Nagas','Avoid',57);
insert into MinderRankingDetail values(514,'Demons','Irrellevant',58);
insert into MinderRankingDetail values(515,'Dragons','Irrellevant',58);
insert into MinderRankingDetail values(516,'Pirates','Irrellevant',58);
insert into MinderRankingDetail values(517,'Quillboar','Helpful',58);
insert into MinderRankingDetail values(518,'Mechs','Need',58);
insert into MinderRankingDetail values(519,'Elementals','Irrellevant',58);
insert into MinderRankingDetail values(520,'Murlocs','Irrellevant',58);
insert into MinderRankingDetail values(521,'Beast','Irrellevant',58);
insert into MinderRankingDetail values(522,'Nagas','Avoid',58);
insert into MinderRankingDetail values(523,'Demons','Irrellevant',59);
insert into MinderRankingDetail values(524,'Dragons','Helpful',59);
insert into MinderRankingDetail values(525,'Pirates','Irrellevant',59);
insert into MinderRankingDetail values(526,'Quillboar','Helpful',59);
insert into MinderRankingDetail values(527,'Mechs','Need',59);
insert into MinderRankingDetail values(528,'Elementals','Helpful',59);
insert into MinderRankingDetail values(529,'Murlocs','Irrellevant',59);
insert into MinderRankingDetail values(530,'Beast','Irrellevant',59);
insert into MinderRankingDetail values(531,'Nagas','Avoid',59);
insert into MinderRankingDetail values(532,'Demons','Irrellevant',60);
insert into MinderRankingDetail values(533,'Dragons','Irrellevant',60);
insert into MinderRankingDetail values(534,'Pirates','Helpful',60);
insert into MinderRankingDetail values(535,'Quillboar','Helpful',60);
insert into MinderRankingDetail values(536,'Mechs','Irrellevant',60);
insert into MinderRankingDetail values(537,'Elementals','Helpful',60);
insert into MinderRankingDetail values(538,'Murlocs','Helpful',60);
insert into MinderRankingDetail values(539,'Beast','Avoid',60);
insert into MinderRankingDetail values(540,'Nagas','Helpful',60);
insert into MinderRankingDetail values(541,'Demons','Avoid',61);
insert into MinderRankingDetail values(542,'Dragons','Avoid',61);
insert into MinderRankingDetail values(543,'Pirates','Helpful',61);
insert into MinderRankingDetail values(544,'Quillboar','Irrellevant',61);
insert into MinderRankingDetail values(545,'Mechs','Avoid',61);
insert into MinderRankingDetail values(546,'Elementals','Irrellevant',61);
insert into MinderRankingDetail values(547,'Murlocs','Irrellevant',61);
insert into MinderRankingDetail values(548,'Beast','Helpful',61);
insert into MinderRankingDetail values(549,'Nagas','Helpful',61);
insert into MinderRankingDetail values(550,'Demons','Avoid',62);
insert into MinderRankingDetail values(551,'Dragons','Avoid',62);
insert into MinderRankingDetail values(552,'Pirates','Helpful',62);
insert into MinderRankingDetail values(553,'Quillboar','Helpful',62);
insert into MinderRankingDetail values(554,'Mechs','Irrellevant',62);
insert into MinderRankingDetail values(555,'Elementals','Irrellevant',62);
insert into MinderRankingDetail values(556,'Murlocs','Helpful',62);
insert into MinderRankingDetail values(557,'Beast','Helpful',62);
insert into MinderRankingDetail values(558,'Nagas','Irrellevant',62);
insert into MinderRankingDetail values(559,'Demons','Helpful',63);
insert into MinderRankingDetail values(560,'Dragons','Irrellevant',63);
insert into MinderRankingDetail values(561,'Pirates','Irrellevant',63);
insert into MinderRankingDetail values(562,'Quillboar','Helpful',63);
insert into MinderRankingDetail values(563,'Mechs','Helpful',63);
insert into MinderRankingDetail values(564,'Elementals','Irrellevant',63);
insert into MinderRankingDetail values(565,'Murlocs','Irrellevant',63);
insert into MinderRankingDetail values(566,'Beast','Irrellevant',63);
insert into MinderRankingDetail values(567,'Nagas','Irrellevant',63);
insert into MinderRankingDetail values(568,'Demons','Irrellevant',64);
insert into MinderRankingDetail values(569,'Dragons','Avoid',64);
insert into MinderRankingDetail values(570,'Pirates','Helpful',64);
insert into MinderRankingDetail values(571,'Quillboar','Helpful',64);
insert into MinderRankingDetail values(572,'Mechs','Helpful',64);
insert into MinderRankingDetail values(573,'Elementals','Irrellevant',64);
insert into MinderRankingDetail values(574,'Murlocs','Irrellevant',64);
insert into MinderRankingDetail values(575,'Beast','Irrellevant',64);
insert into MinderRankingDetail values(576,'Nagas','Helpful',64);
insert into MinderRankingDetail values(577,'Demons','Irrellevant',65);
insert into MinderRankingDetail values(578,'Dragons','Helpful',65);
insert into MinderRankingDetail values(579,'Pirates','Irrellevant',65);
insert into MinderRankingDetail values(580,'Quillboar','Helpful',65);
insert into MinderRankingDetail values(581,'Mechs','Helpful',65);
insert into MinderRankingDetail values(582,'Elementals','Irrellevant',65);
insert into MinderRankingDetail values(583,'Murlocs','Irrellevant',65);
insert into MinderRankingDetail values(584,'Beast','Avoid',65);
insert into MinderRankingDetail values(585,'Nagas','Avoid',65);
insert into MinderRankingDetail values(586,'Demons','Irrellevant',66);
insert into MinderRankingDetail values(587,'Dragons','Irrellevant',66);
insert into MinderRankingDetail values(588,'Pirates','Irrellevant',66);
insert into MinderRankingDetail values(589,'Quillboar','Irrellevant',66);
insert into MinderRankingDetail values(590,'Mechs','Avoid',66);
insert into MinderRankingDetail values(591,'Elementals','Irrellevant',66);
insert into MinderRankingDetail values(592,'Murlocs','Helpful',66);
insert into MinderRankingDetail values(593,'Beast','Irrellevant',66);
insert into MinderRankingDetail values(594,'Nagas','Irrellevant',66);
insert into MinderRankingDetail values(595,'Demons','Avoid',67);
insert into MinderRankingDetail values(596,'Dragons','Avoid',67);
insert into MinderRankingDetail values(597,'Pirates','Irrellevant',67);
insert into MinderRankingDetail values(598,'Quillboar','Helpful',67);
insert into MinderRankingDetail values(599,'Mechs','Irrellevant',67);
insert into MinderRankingDetail values(600,'Elementals','Helpful',67);
insert into MinderRankingDetail values(601,'Murlocs','Helpful',67);
insert into MinderRankingDetail values(602,'Beast','Irrellevant',67);
insert into MinderRankingDetail values(603,'Nagas','Helpful',67);
insert into MinderRankingDetail values(604,'Demons','Irrellevant',68);
insert into MinderRankingDetail values(605,'Dragons','Irrellevant',68);
insert into MinderRankingDetail values(606,'Pirates','Irrellevant',68);
insert into MinderRankingDetail values(607,'Quillboar','Helpful',68);
insert into MinderRankingDetail values(608,'Mechs','Irrellevant',68);
insert into MinderRankingDetail values(609,'Elementals','Irrellevant',68);
insert into MinderRankingDetail values(610,'Murlocs','Helpful',68);
insert into MinderRankingDetail values(611,'Beast','Irrellevant',68);
insert into MinderRankingDetail values(612,'Nagas','Helpful',68);
insert into MinderRankingDetail values(613,'Demons','Irrellevant',69);
insert into MinderRankingDetail values(614,'Dragons','Irrellevant',69);
insert into MinderRankingDetail values(615,'Pirates','Helpful',69);
insert into MinderRankingDetail values(616,'Quillboar','Helpful',69);
insert into MinderRankingDetail values(617,'Mechs','Irrellevant',69);
insert into MinderRankingDetail values(618,'Elementals','Irrellevant',69);
insert into MinderRankingDetail values(619,'Murlocs','Irrellevant',69);
insert into MinderRankingDetail values(620,'Beast','Helpful',69);
insert into MinderRankingDetail values(621,'Nagas','Avoid',69);
insert into MinderRankingDetail values(622,'Demons','Helpful',70);
insert into MinderRankingDetail values(623,'Dragons','Irrellevant',70);
insert into MinderRankingDetail values(624,'Pirates','Irrellevant',70);
insert into MinderRankingDetail values(625,'Quillboar','Irrellevant',70);
insert into MinderRankingDetail values(626,'Mechs','Helpful',70);
insert into MinderRankingDetail values(627,'Elementals','Irrellevant',70);
insert into MinderRankingDetail values(628,'Murlocs','Avoid',70);
insert into MinderRankingDetail values(629,'Beast','Irrellevant',70);
insert into MinderRankingDetail values(630,'Nagas','Avoid',70);
insert into MinderRankingDetail values(631,'Demons','Irrellevant',71);
insert into MinderRankingDetail values(632,'Dragons','Irrellevant',71);
insert into MinderRankingDetail values(633,'Pirates','Irrellevant',71);
insert into MinderRankingDetail values(634,'Quillboar','Irrellevant',71);
insert into MinderRankingDetail values(635,'Mechs','Irrellevant',71);
insert into MinderRankingDetail values(636,'Elementals','Irrellevant',71);
insert into MinderRankingDetail values(637,'Murlocs','Irrellevant',71);
insert into MinderRankingDetail values(638,'Beast','Irrellevant',71);
insert into MinderRankingDetail values(639,'Nagas','Helpful',71);
insert into MinderRankingDetail values(640,'Demons','Irrellevant',72);
insert into MinderRankingDetail values(641,'Dragons','Helpful',72);
insert into MinderRankingDetail values(642,'Pirates','Irrellevant',72);
insert into MinderRankingDetail values(643,'Quillboar','Helpful',72);
insert into MinderRankingDetail values(644,'Mechs','Helpful',72);
insert into MinderRankingDetail values(645,'Elementals','Irrellevant',72);
insert into MinderRankingDetail values(646,'Murlocs','Irrellevant',72);
insert into MinderRankingDetail values(647,'Beast','Irrellevant',72);
insert into MinderRankingDetail values(648,'Nagas','Avoid',72);
insert into MinderRankingDetail values(649,'Demons','Irrellevant',73);
insert into MinderRankingDetail values(650,'Dragons','Irrellevant',73);
insert into MinderRankingDetail values(651,'Pirates','Irrellevant',73);
insert into MinderRankingDetail values(652,'Quillboar','Helpful',73);
insert into MinderRankingDetail values(653,'Mechs','Irrellevant',73);
insert into MinderRankingDetail values(654,'Elementals','Irrellevant',73);
insert into MinderRankingDetail values(655,'Murlocs','Helpful',73);
insert into MinderRankingDetail values(656,'Beast','Irrellevant',73);
insert into MinderRankingDetail values(657,'Nagas','Avoid',73);
insert into MinderRankingDetail values(658,'Demons','Irrellevant',74);
insert into MinderRankingDetail values(659,'Dragons','Irrellevant',74);
insert into MinderRankingDetail values(660,'Pirates','Helpful',74);
insert into MinderRankingDetail values(661,'Quillboar','Helpful',74);
insert into MinderRankingDetail values(662,'Mechs','Irrellevant',74);
insert into MinderRankingDetail values(663,'Elementals','Helpful',74);
insert into MinderRankingDetail values(664,'Murlocs','Irrellevant',74);
insert into MinderRankingDetail values(665,'Beast','Helpful',74);
insert into MinderRankingDetail values(666,'Nagas','Helpful',74);
insert into MinderRankingDetail values(667,'Demons','Irrellevant',75);
insert into MinderRankingDetail values(668,'Dragons','Irrellevant',75);
insert into MinderRankingDetail values(669,'Pirates','Irrellevant',75);
insert into MinderRankingDetail values(670,'Quillboar','Helpful',75);
insert into MinderRankingDetail values(671,'Mechs','Irrellevant',75);
insert into MinderRankingDetail values(672,'Elementals','Irrellevant',75);
insert into MinderRankingDetail values(673,'Murlocs','Helpful',75);
insert into MinderRankingDetail values(674,'Beast','Irrellevant',75);
insert into MinderRankingDetail values(675,'Nagas','Irrellevant',75);
insert into MinderRankingDetail values(676,'Demons','Irrellevant',76);
insert into MinderRankingDetail values(677,'Dragons','Need',76);
insert into MinderRankingDetail values(678,'Pirates','Irrellevant',76);
insert into MinderRankingDetail values(679,'Quillboar','Irrellevant',76);
insert into MinderRankingDetail values(680,'Mechs','Helpful',76);
insert into MinderRankingDetail values(681,'Elementals','Irrellevant',76);
insert into MinderRankingDetail values(682,'Murlocs','Irrellevant',76);
insert into MinderRankingDetail values(683,'Beast','Irrellevant',76);
insert into MinderRankingDetail values(684,'Nagas','Avoid',76);
insert into MinderRankingDetail values(685,'Demons','Irrellevant',77);
insert into MinderRankingDetail values(686,'Dragons','Irrellevant',77);
insert into MinderRankingDetail values(687,'Pirates','Irrellevant',77);
insert into MinderRankingDetail values(688,'Quillboar','Helpful',77);
insert into MinderRankingDetail values(689,'Mechs','Helpful',77);
insert into MinderRankingDetail values(690,'Elementals','Irrellevant',77);
insert into MinderRankingDetail values(691,'Murlocs','Irrellevant',77);
insert into MinderRankingDetail values(692,'Beast','Irrellevant',77);
insert into MinderRankingDetail values(693,'Nagas','Irrellevant',77);
insert into MinderRankingDetail values(694,'Demons','Avoid',78);
insert into MinderRankingDetail values(695,'Dragons','Avoid',78);
insert into MinderRankingDetail values(696,'Pirates','Helpful',78);
insert into MinderRankingDetail values(697,'Quillboar','Helpful',78);
insert into MinderRankingDetail values(698,'Mechs','Avoid',78);
insert into MinderRankingDetail values(699,'Elementals','Helpful',78);
insert into MinderRankingDetail values(700,'Murlocs','Irrellevant',78);
insert into MinderRankingDetail values(701,'Beast','Helpful',78);
insert into MinderRankingDetail values(702,'Nagas','Avoid',78);
insert into MinderRankingDetail values(703,'Demons','Irrellevant',79);
insert into MinderRankingDetail values(704,'Dragons','Helpful',79);
insert into MinderRankingDetail values(705,'Pirates','Helpful',79);
insert into MinderRankingDetail values(706,'Quillboar','Helpful',79);
insert into MinderRankingDetail values(707,'Mechs','Helpful',79);
insert into MinderRankingDetail values(708,'Elementals','Irrellevant',79);
insert into MinderRankingDetail values(709,'Murlocs','Avoid',79);
insert into MinderRankingDetail values(710,'Beast','Avoid',79);
insert into MinderRankingDetail values(711,'Nagas','Helpful',79);
insert into MinderRankingDetail values(712,'Demons','Helpful',80);
insert into MinderRankingDetail values(713,'Dragons','Avoid',80);
insert into MinderRankingDetail values(714,'Pirates','Irrellevant',80);
insert into MinderRankingDetail values(715,'Quillboar','Irrellevant',80);
insert into MinderRankingDetail values(716,'Mechs','Need',80);
insert into MinderRankingDetail values(717,'Elementals','Irrellevant',80);
insert into MinderRankingDetail values(718,'Murlocs','Irrellevant',80);
insert into MinderRankingDetail values(719,'Beast','Irrellevant',80);
insert into MinderRankingDetail values(720,'Nagas','Avoid',80);
